### PR TITLE
fix: uproot -> uproot3

### PR DESCRIPTION
**Pull request by andrzejnovak**
uproot now points to uproot4, syntax is a bit different

### CODE REVIEW

**Comment by jkiesele** [comment]
Thanks.
I will merge once a new base container is created.

**Comment by jkiesele** [comment]
Actually, thinking about the different syntax.
How different? I don't want to create issues downstream in other people's repositories without warning.
(e.g. does uproot3 warn you about the changed syntax?)

**Comment by andrzejnovak** [comment]
"uproot" until last weekend pointed to `uproot3`, it now points to `uproot4`. So this is just a fix to keep everything unchanged for this.

At some point DJC calls `.array()` on an uproot loaded file, which now crashes bc that syntax doesn't exist in uproot4

**Comment by jkiesele** [comment]
I see, I didn't understand correctly first.
Thanks! that is indeed useful (the container creation is running anyway)

**Pull request merged**
