### PR TITLE
Initiating full_logs from log file in case it already exists one (e.g…

### PR DESCRIPTION
**Pull request by pfs**
…. in nested trainings)

### CODE REVIEW

**Comment by jkiesele** [comment]
Doesn't this part already do the same?
https://github.com/DL4Jets/DeepJetCore/blob/master/training/DeepJet_callbacks.py#L77-L85

**Comment by pfs** [comment]
@jkiesele interesting i didn't have that part locally for some reason. The issue with that is that if you load it always at epoch end and re-write it will repeat all the N-1 epochs.
E.g. if one doing a nested training of 3 parameters with 2 epochs per parameter, the final full_info will have 9 entries instead of 6.

**Comment by jkiesele** [comment]
@pfs I might still be slow this morning, but I don't really follow why it would create 9 entries. If you have such a training, it would
finish epoch 0.1: create new file
finish epoch 0.2: load (0.1) and add.
--new parameter --
finish epoch 1.1: load (0.1,0.2) and add
finish epoch 1.2: load (0.1,0.2,1.1) and add 
...
That makes me count to six.

**Comment by pfs** [comment]
@jkiesele you're right :) ignore this PR, for some reason my master is different at this point
https://github.com/pfs/DeepJetCore/blob/master/training/DeepJet_callbacks.py#L42
and was missing some feature like this and this PR was the implementation 
but now i see that the current master is just fine :) thanks!

**Pull request closed without merging**
